name: http_helper
description: The http_helper is a powerful yet easy-to-use HTTP networking library for Dart, designed to encapsulate the complexities of making HTTP requests in client applications.

version: 1.2.2

repository: https://github.com/OakWings/http_helper

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

  build_runner: ^2.4.5
